version: '3.9'
services:
  sistema_nginx:
    container_name: sistema_nginx_container
    build:
      dockerfile: nginx/Dockerfile
      context: nginx/
    image: nginx_didox
    ports: 
      - "80:80"
    depends_on:
      - sistema_java1
      - sistema_java2
      - sistema_java3
    networks:
      - anima-network
  sistema_java1:
    container_name: sistema_nginx_container_1
    image: didox/validador-cpf-java-turma-devops
    command: sh -c "echo 'bem vindo ao container 1'"
    networks:
      - anima-network
  sistema_java2:
    container_name: sistema_nginx_container_2
    image: didox/validador-cpf-java-turma-devops
    command: sh -c "echo 'bem vindo ao container 2'"
    networks:
      - anima-network
  sistema_java3:
    container_name: sistema_nginx_container_3
    image: didox/validador-cpf-java-turma-devops
    command: sh -c "echo 'bem vindo ao container 2'"
    networks:
      - anima-network

networks: 
  anima-network:
    driver: bridge